### ISSUE TITLE
missing: 3d-pose-baseline/src/../data/h36m/metadata.xml'

### ISSUE THREAD

**Issue by benjaminabruzzo** [ArashHosseini/3d-pose-baseline#21]
Trying to get the pre-trained model to run, but this config seems to be missing.

Traceback (most recent call last):
  File "src/predict_3dpose.py", line 524, in <module>
    tf.compat.v1.app.run()
  File "/home/benjamin/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/benjamin/anaconda3/envs/tf/lib/python3.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/benjamin/anaconda3/envs/tf/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "src/predict_3dpose.py", line 519, in main
    sample()
  File "src/predict_3dpose.py", line 397, in sample
    rcams = cameras.load_cameras(os.path.join(this_file, "..", FLAGS.cameras_path), SUBJECT_IDS)
  File "/home/benjamin/reverie/pose3d/3d-pose-baseline/src/cameras.py", line 162, in load_cameras
    xmldoc = minidom.parse(bpath)
  File "/home/benjamin/anaconda3/envs/tf/lib/python3.7/xml/dom/minidom.py", line 1958, in parse
    return expatbuilder.parse(file)
  File "/home/benjamin/anaconda3/envs/tf/lib/python3.7/xml/dom/expatbuilder.py", line 910, in parse
    with open(file, 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/home/benjamin/3d-pose-baseline/src/../data/h36m/metadata.xml'

**Comment by Pan-Mengyu** [comment]
you can download the code-v1.2.zip file in http://vision.imar.ro/human3.6m/, unzip it, and copy the metadata.xml file under data/h36m/
